application: ukinflation
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: public/css

- url: /tasks/scrape-rpi
  script: scrape-rpi.py
  login: admin

- url: .*
  script: main.py
